version: 2
updates:
  - package-ecosystem: pip
    directory: "/functions/GreetingFunction/"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: "/ui/pages/Foundry JS Demo/"
    open-pull-requests-limit: 10
    schedule:
      interval: weekly
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "actions/setup-node"
        versions: [">=6.2.0"]
